<?php

namespace App\Traits;

trait AuthorizesMarketRequest
{
    public function resolveAutorization(&$queryParams,&$formParams,&$headers)
    {
        $accessToken = $this->resolveAccessToken();
        $headers['Authorization'] = $accessToken;
    }

    public function resolveAccessToken()
    {
        return 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImUyOGVmNTU5NWY2MjVkMDg0ZTBkNTY2MGM2MzY1NmFkODE1ODE4YmJhMTQ4MWQ0OTZjN2EyMWY1MmRiZDQwNDMzOTcwNWRkMGFmZTBiNTNlIn0.eyJhdWQiOiIyIiwianRpIjoiZTI4ZWY1NTk1ZjYyNWQwODRlMGQ1NjYwYzYzNjU2YWQ4MTU4MThiYmExNDgxZDQ5NmM3YTIxZjUyZGJkNDA0MzM5NzA1ZGQwYWZlMGI1M2UiLCJpYXQiOjE1NjY2ODU4MjIsIm5iZiI6MTU2NjY4NTgyMiwiZXhwIjoxNTk4MzA4MjIyLCJzdWIiOiIxMDg3Iiwic2NvcGVzIjpbInB1cmNoYXNlLXByb2R1Y3QiLCJtYW5hZ2UtcHJvZHVjdHMiLCJtYW5hZ2UtYWNjb3VudCIsInJlYWQtZ2VuZXJhbCJdfQ.P4Jv0CUhAGYaJaSGt-8p474GwqcXdjgK3kuZTjpvAaWSZdMzaLWXRpSuDfcJR5ZJsm366yEQ-WqnGlzOwIeGcQYzK7I68WqOVCBovp_evfVusYCCBvQbK3WuJB2ZAyacS2VO4vu5wLMVZ1wMnuh_lHDEtgacMG_kB8dzgZRfHyi6hXqWPt_wLFybCUWRGc5vOBt2dDp-WcVT2ZcnSims3f3R8AXVlWNgwPPfJ1tzbXA4SB5S1ps47PkazTHKgnjCz2laAH-jzVIGdg9jpsJNjC5tIup_esXGD-8bcODXJiiP3eVeYph3srEsjj80oIcDTKC648efMtaSo5ouvXJx7XiIbY7a9Y_SP7gc2fMYvi83FHiY9-1SyhEQiVpSjGUiWTL1g42BbOYrMjqqTh00NLJQEo_I4n7WH2uTrEhvS-gd_ix3eLChVhakLnbIhkRPeq_q_KEKKy25JxbSiicI1ZtAGC1quJhHrazXKRzrnS_zuhjSCHhLjctOh6wF5jqFLjbDqpJ7yVBuVzdtLvnVvrRlaGNbtM_oCYOioC3jdJx1Q6b7aUGYzeRSZN1uWASJbs5PuCgJ9bZL2_wBDHSrw6mJHuEbmrssi3c-EiAZhseO0kXBY7JoguCIVLEeIfSAA-MnaBBhBo4O2KHT2jJmpWkYtO2AzmQcjt4NQ6Upgd8';
    }

}